apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: insurance-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: insurance
  template:
    metadata:
      name: insurance
    spec:
      containers:
        - name: insurance
          image: gcr.io/pycaret-deployment-kubernetes/insurance:v3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
